= verifymedia(1)
:doctype: manpage
:manmanual: User Commands
:mansource: verifymedia {version}

== Name

verifymedia - Verfiy SUSE installation or Live ISO images.


== Synopsis

*verifymedia* _ISO_


== Description

verifymedia checks SUSE bootable installation or Live media for technical correctness.


=== General Options

*--ignore*=_TOPIC_::
Ignore specific test result. The test is still run but any failures are not counted.
TOPIC is the test topic as shown in the test report.
The option can be repeated to exclude several tests.

*--verbose*::
Show more detailed messages. Can be repeated to log even more.

*--version*::
Show verifymedia version.

*--save-temp*::
Keep temporary files.

*--help*::
Show this help text.

=== Default list of ignored tests

The result of some tests is ignored by default - making them optional checks:

- "UEFI boot image exists",
-  "ISO digest is md5",
- "boot partition is EFI System Partition"

== See Also

*mkmedia*(1), *checkmedia*(1), *tagmedia*(1).

== Links

- more documentation: `/usr/share/doc/packages/mksusecd` +
- get latest version: https://github.com/openSUSE/mksusecd?tab=readme-ov-file#downloads +
- mksusecd web site: https://github.com/openSUSE/mksusecd +
- openSUSE Build Service: https://build.opensuse.org
